services:
  huebuildstatus:
    build:
      context: .
      dockerfile: HueBuildStatus.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - bridgeIp=
      - bridgeKey=
      - LightName=